# Site settings
title: Simon Pepin Lehalleur
email:  simonpl@zedat.fu-berlin.de 
description: > # this means to ignore newlines until "baseurl:"
  I'm a post-doctoral student at the Freie Universität Berlin.
  I study Arithmetic Geometry.
# baseurl: "/" # the subpath of your site, e.g. /blog/
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
