# Site settings
title: Simon Pepin Lehalleur
email:  simon.pepin.lehalleur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Postdoctoral researcher in algebraic geometry at the University of Amsterdam
# baseurl: "/" # the subpath of your site, e.g. /blog/
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
