# Site settings
title: Simon Pepin Lehalleur
email:  simon.pepinlehalleur@ru.nl 
description: > # this means to ignore newlines until "baseurl:"
  Postdoc in arithmetic geometry at Radboud University
# baseurl: "/" # the subpath of your site, e.g. /blog/
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
